#!/bin/bash
MAXCPUS=${MAXCPUS:=1}
MAXNCPUSPCT=${MAXNCPUSPCT:=25.000000}
CPU_USAGE_LIMIT=${CPU_USAGE_LIMIT:=100}
F="cc_config.xml gui_rpc_auth.cfg remote_hosts.cfg"
for file in $F; do
  if [ ! -f /var/lib/boinc-client/$file ]; then
    cp /etc/boinc-client/$file /var/lib/boinc-client/
  fi
done
if [ ! -e /var/lib/boinc-client/ca-bundle.crt ]; then
  ln -s /etc/ssl/certs/ca-certificates.crt /var/lib/boinc-client/ca-bundle.crt
fi
cat > /var/lib/boinc-client/global_prefs_override.xml <<EOF
<global_preferences>
<max_cpus>${MAXCPUS}</max_cpus>
<max_ncpus_pct>${MAXNCPUSPCT}</max_ncpus_pct>
<suspend_cpu_usage>0</suspend_cpu_usage>
<run_if_user_active>1</run_if_user_active>
<cpu_usage_limit>${CPU_USAGE_LIMIT}</cpu_usage_limit>
</global_preferences>
EOF
mkdir -p /dev/input/mice

if [ -n "$1" ]; then
  exec "$@"
fi
exec /usr/bin/boinc --dir /var/lib/boinc-client
